# Generated by Django 5.1.3 on 2024-12-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_soin', models.JSONField()),
                ('type_soin', models.CharField(max_length=100)),
                ('etat_patient', models.CharField(max_length=100)),
                ('observation', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
