# Generated by Django 5.1.3 on 2024-12-16 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('care', '0001_initial'),
        ('consultations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soin',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultations.consultation'),
        ),
        migrations.AddField(
            model_name='soin',
            name='infermier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.infermie'),
        ),
    ]
