# Generated by Django 5.1.4 on 2024-12-27 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soin',
            name='data_soin',
        ),
    ]
