# Generated by Django 5.1.3 on 2024-12-16 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_validation', models.JSONField()),
                ('valid_state', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('dose', models.IntegerField()),
                ('duree', models.IntegerField()),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultations.ordonnance')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('diagnostic', models.TextField()),
                ('resume', models.TextField(blank=True, null=True)),
                ('dpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.dpi')),
                ('ordonnance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultations.ordonnance')),
            ],
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='validation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultations.validation'),
        ),
    ]
