# Generated by Django 5.1.4 on 2024-12-27 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='dpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.dpi'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='ordonnance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='consultations.ordonnance'),
        ),
        migrations.AlterField(
            model_name='validation',
            name='data_validation',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
