# Generated by Django 5.1.3 on 2024-12-15 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('antecedants', models.TextField(blank=True, null=True)),
                ('bilan_biologique', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nss', models.CharField(max_length=14, unique=True)),
                ('date_naissance', models.DateField()),
                ('addresse', models.CharField(max_length=100)),
                ('mutuelle', models.TextField()),
                ('personne_contact', models.CharField(blank=True, max_length=12, null=True)),
                ('dpi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.dpi')),
                ('medcin_traitant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.medcin')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
