# Generated by Django 5.1.4 on 2024-12-27 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='laborantin',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='radiologue',
        ),
        migrations.AddField(
            model_name='examen',
            name='technicien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='type_examen',
            field=models.CharField(choices=[('biologique', 'Biologique'), ('radiologique', 'Radiologique')], max_length=20),
        ),
    ]
